#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Virtual
DECORATOR_VIRTUAL = 'V'

# Origin of declaration
DECLARATION_FROM_MODULE = "MODULE"
DECLARATION_FROM_CLASS = "CLASS"
DECLARATION_FROM_INSTANCE = "OBJECT"

# Type Separator
BEGINTYPE_SEPARATOR = 'B'
ENDTYPE_SEPARATOR = 'E'

# Node Type
NODE_PRIMARYTYPE_CHAR = 'n'
NODE_COMPOSEDTYPE_CHAR = 'c'
NODE_FUNCTYPE_CHAR = 'f'
NODE_QUALTYPE_CHAR = 'q'
NODE_POINTERTYPE_CHAR = 'p'
NODE_ARRAYTYPE_CHAR = 'a'
NODE_NONETYPE_CHAR = 'o'
NODE_PARENTYPE_CHAR = 't'

# Nativ Types
NATIVTYPE_ELLIPSIS = 'Z'
NATIVTYPE_SIGNED_CHAR = 'C'
NATIVTYPE_CHAR = 'D'
NATIVTYPE_UNSIGNED_CHAR = 'E'
NATIVTYPE_SHORT_INT = 'F'
NATIVTYPE_UNSIGNED_SHORT_INT = 'G'
NATIVTYPE_INT = 'H'
NATIVTYPE_UNSIGNED_INT = 'I'
NATIVTYPE_LONG_INT = 'J'
NATIVTYPE_UNSIGNED_LONG_INT = 'K'
NATIVTYPE_FLOAT = 'M'
NATIVTYPE_DOUBLE = 'N'
NATIVTYPE_LONG_DOUBLE = 'O'
NATIVTYPE_VOID = 'X'

# Other Type
USERTYPE_TYPEDEF = 'T'
USERTYPE_ENUM = 'V'
USERTYPE_UNION = 'U'
USERTYPE_STRUCT = 'S'
USERTYPE_NATIV = 'W'

# Qualifier
QUALIFIER_CONST = 'c'
QUALIFIER_VOLATILE = 'l'

# Declaration Kind
DECLARATION_STATIC = 'S'
DECLARATION_AUTO =  'A'
