typedef int toto;
int variable;
static long unsigned int variable;
int variable[69];
extern void *variable;
const int *variable;
static int * const variable;
volatile unsigned short *variable[42];
void **(**functionPointer)(int);
struct int *function(void **, int, ...);
static double (*functionPointer)(toto **, int, ...);
volatile void (*functionPointer)(void const (*)(int));
